export default {
    name:'product',
    title:'Product',
    type:'document',
    fields:[
        {
            name:'image',
            title:'Image',
            type:'array',
            of:[{type:'image'}],
            Option:{
                hotspot:true
            }
        },
        {
            name:'name',
            title:'Name',
            type:'string',
        },
        {
            name:'slug',
            title:'Slug',
            type:'slug',
            options:{
                source:'name',
                maxLength:100,
            }
        },
        {
            name:'description',
            title:'Description',
            type:'text',
        },
        {
            name:'price',
            title:'Price',
            type:'number',
        },
       
    ],
    
}